//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurseIO.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WordList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WordList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurseIO.Data.WordList", typeof(WordList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4r5e
        ///5h1t
        ///5hit
        ///sh1t
        ///a55
        ///anal
        ///anus
        ///ar5e
        ///arrse
        ///arse
        ///ass
        ///ass-fucker
        ///asses
        ///assfucker
        ///assfukka
        ///asshole
        ///assholes
        ///asswhole
        ///a_s_s
        ///b!tch
        ///b00bs
        ///b17ch
        ///b1tch
        ///ballbag
        ///ballsack
        ///bastard
        ///beastial
        ///beastiality
        ///bellend
        ///bestial
        ///bestiality
        ///bi+ch
        ///biatch
        ///bitch
        ///bitcher
        ///bitchers
        ///bitches
        ///bitchin
        ///bitching
        ///bloody
        ///blow job
        ///blowjob
        ///blowjobs
        ///boiolas
        ///bollock
        ///bollok
        ///boner
        ///boob
        ///boobs
        ///booobs
        ///boooobs
        ///booooobs
        ///booooooobs
        ///breasts
        ///bugger
        ///bum
        ///bunny fucker
        ///butt
        ///butthole
        ///buttmuch
        ///buttplug        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baiser
        ///bander
        ///bigornette
        ///bite
        ///bitte
        ///bloblos
        ///bordel
        ///bosser
        ///bourré
        ///bourrée
        ///brackmard
        ///branlage
        ///branler
        ///branlette
        ///branleur
        ///branleuse
        ///brouter le cresson
        ///caca
        ///cailler
        ///chatte
        ///chiasse
        ///chier
        ///chiottes
        ///clito
        ///clitoris
        ///con
        ///connard
        ///connasse
        ///conne
        ///couilles
        ///cramouille
        ///cul
        ///déconne
        ///déconner
        ///drague
        ///emmerdant
        ///emmerder
        ///emmerdeur
        ///emmerdeuse
        ///enculé
        ///enculée
        ///enculeur
        ///enculeurs
        ///enfoiré
        ///enfoirée
        ///étron
        ///fille de pute
        ///fils de pute
        ///folle
        ///foutre
        ///gerbe
        ///gerber
        ///gouine
        ///grande folle
        ///grognia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to analritter
        ///arsch
        ///arschficker
        ///arschlecker
        ///arschloch
        ///bimbo
        ///bratze
        ///bumsen
        ///bonze
        ///dödel
        ///fick
        ///ficken
        ///flittchen
        ///fotze
        ///fratze
        ///hackfresse
        ///hure
        ///hurensohn
        ///ische
        ///kackbratze
        ///kacke
        ///kacken
        ///kackwurst
        ///kampflesbe
        ///kanake
        ///kimme
        ///lümmel
        ///MILF
        ///möpse
        ///morgenlatte
        ///möse
        ///mufti
        ///muschi
        ///nackt
        ///neger
        ///nigger
        ///nippel
        ///nutte
        ///onanieren
        ///orgasmus
        ///pimmel
        ///pimpern
        ///pinkeln
        ///pissen
        ///pisser
        ///popel
        ///poppen
        ///porno
        ///reudig
        ///rosette
        ///schabracke
        ///schlampe
        ///scheiße
        ///scheisser
        ///schiesser
        ///schnackeln
        ///schwanzlutscher
        ///sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allupato
        ///ammucchiata
        ///anale
        ///arrapato
        ///arrusa
        ///arruso
        ///assatanato
        ///bagascia
        ///bagassa
        ///bagnarsi
        ///baldracca
        ///balle
        ///battere
        ///battona
        ///belino
        ///biga
        ///bocchinara
        ///bocchino
        ///bofilo
        ///boiata
        ///bordello
        ///brinca
        ///bucaiolo
        ///budiùlo
        ///buona donna
        ///busone
        ///cacca
        ///caccati in mano e prenditi a schiaffi
        ///caciocappella
        ///cadavere
        ///cagare
        ///cagata
        ///cagna
        ///cammello
        ///cappella
        ///carciofo
        ///carità
        ///casci
        ///cazzata
        ///cazzimma
        ///cazzo
        ///checca
        ///chiappa
        ///chiavare
        ///chiavata
        ///ciospo
        ///ciucciami il cazzo
        ///coglione
        ///coglioni
        ///cornuto
        ///cozza
        ///cul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asno
        ///bastardo
        ///Bollera
        ///Cabron
        ///Cabrón
        ///Chupada
        ///Chupapollas
        ///Chupetón
        ///concha
        ///Concha de tu madre
        ///Coño
        ///Coprofagía
        ///Culo
        ///Drogas
        ///Follador
        ///Follar
        ///Gilipichis
        ///Gilipollas
        ///Hacer una paja
        ///Haciendo el amor
        ///Heroína
        ///Hija de puta
        ///Hijaputa
        ///Hijo de puta
        ///Hijoputa
        ///Idiota
        ///Imbécil
        ///infierno
        ///Jilipollas
        ///Kapullo
        ///Lameculos
        ///Maciza
        ///Macizorra
        ///maldito
        ///Mamada
        ///Marica
        ///Maricón
        ///Mariconazo
        ///martillo
        ///Mierda
        ///Nazi
        ///Orina
        ///Pedo
        ///Pervertido
        ///Pezón
        ///Pinche
        ///Pis
        ///Prostituta
        ///Puta
        ///Racista
        ///Ramera
        ///Sádico
        ///Semen
        ///Sex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
    }
}
